version: '3.1'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: example
      MYSQL_PASSWORD: example      
    ports:
      - "3060:3060"